
<div class="container"> 
    <form method="post">
        <div class="form-group">
            <label for="idBosses">Boss</label>
            <select name="idBosses" id="idBosses" class="custom-select regselect" required>
                <?php
                foreach ($bosses as $boss) {
                $diffName = dbget::toName("difficulty", $boss[2]);
                ?><option value=<?= $boss[0] ?>><?= $boss[1] . " " . $diffName[0]?></option>
                <?php
                }
                ?>
            </select>
        </div>
        <div class="form-group">
            <label for="idItems">Item</label>
            <select class="custom-select regselect" style="color: black;" name="idItems" required>
                <?php
                foreach ($items as $item) {
                ?><option value=<?= $item[0] ?>><?= $item[1] ?></option>
                <?php
                }
                ?>
            </select>

        </div>
        <button type="submit" class="btn btn-secondary">Push</button>
    </form>
</div>
<div class="container">
    <table class="table regtable">
        <thead>
            <tr>
                <th scope="col">Boss</th>
                <th scope="col">Item</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($bossitems as $bossitem) {
                $bosses = dbget::toName("bosses", $bossitem["idBosses"]);
                $item = dbget::toName("items", $bossitem["idItems"]);
                $b = dbget::getByID("bosses", $bossitem["idBosses"]);
                $namediff = dbget::toName("difficulty", $b["difficulty"]);
            ?>
                <tr>
                    <td><?= $bosses[0] . " " . $namediff[0] ?></td>
                    <td><?= $item[0] ?></td>
                    <td>
                        <a class="btn btn-secondary" href="editbossitem/<?= $bossitem["idBosses"] ?>/<?= $bossitem["idItems"] ?>/delete">Delete</a>
                    </td>
                </tr>
            <?php
            }
            ?>
        </tbody>
    </table>
</div>