<div class="container">
    <form method="post">
        <div class="form-group">
            <label for="nameBoss">Name</label>
            <input type="text" class="form-control" name="nameBoss" id="nameBoss" required>
        </div>
        <div class="form-group">
            <label for="difficulty">Difficulty</label>
            <select name="difficulty" id="difficulty" class="custom-select regselect">   
                <?php
                
                foreach ($difficulties as $diff) {
                ?><option value=<?= $diff[0] ?>><?= $difficulties[1] ?></option>
                <?php
                }
                ?>
            </select>
        </div>
        <div class="form-group">
            <label for="raid">Raid</label>
            <select name="raid" id="raid" class="custom-select regselect">   
                <?php
                
                foreach ($raids as $raid) {
                ?><option value=<?= $raid[0] ?>><?= $raid[1] ?></option>
                <?php
                }
                ?>
            </select>
        </div>
        <button type="submit" class="btn btn-secondary">Push</button>
    </form>
</div>
<div class="container">
    <table class="table regtable">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Difficulty</th>
                <th scope="col">Raid</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($bosses as $boss) {
            ?>
                <tr>
                    <th scope="row"><?= $boss["idBosses"] ?></td>
                    <td><?= $boss["nameBoss"] ?></td>
                    <td><?= $boss["nameDifficulty"] . " " . $boss["pNumber"] ?></td>
                    <td><?= $boss["nameRaid"] ?></td>
                    <td>
                        <a class="btn btn-secondary" href="editboss/<?= $boss["idBosses"] ?>">Edit</a>
                        <a class="btn btn-secondary" href="editboss/<?= $boss["idBosses"] ?>/delete">Delete</a>
                    </td>
                </tr>
            <?php
            }
            ?>
        </tbody>
    </table>
</div>