
<div class="container"> 
    <form method="post">
        <div class="form-group">
            <label for="idBosses">Boss</label>
            <select name="idBosses" id="idBosses" class="custom-select regselect" required>
                <?php
                foreach ($bosses as $boss) {
                ?><option value=<?= $boss["idBosses"] ?>><?= $boss["nameBoss"] . " " . $boss["nameDifficulty"]?></option>
                <?php
                }
                ?>
            </select>
        </div>
        <div class="form-group">
            <label for="idItems">Item</label>
            <select class="custom-select regselect" style="color: black;" name="idItems" required>
                <?php
                foreach ($items as $item) {
                ?><option value=<?= $item[0] ?>><?= $item[1] ?></option>
                <?php
                }
                ?>
            </select>

        </div>
        <button type="submit" class="btn btn-secondary">Push</button>
    </form>
</div>
<div class="container">
    <table class="table regtable">
        <thead>
            <tr>
                <th scope="col">Boss</th>
                <th scope="col">Item</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($bossitems as $bossitem) {
            ?>
                <tr>
                    <td><?= $bossitem["nameBoss"] . " " . $bossitem["nameDifficulty"] ?></td>
                    <td><?= $bossitem["nameItem"] ?></td>
                    <td>
                        <a class="btn btn-secondary" href="editbossitem/<?= $bossitem["idBosses"] ?>/<?= $bossitem["idItems"] ?>/delete">Delete</a>
                    </td>
                </tr>
            <?php
            }
            ?>
        </tbody>
    </table>
</div>