<div class="container">
    <form method="post">
        <div class="form-group">
            <label for="nameCharacter">Name</label>
            <input type="text" class="form-control" name="nameCharacter" id="nameCharacter" required>
        </div>
        <div class="form-group">
            <label for="realmCharacter">Realm</label>
            <select name="realmCharacter" id="realmCharacter" class="custom-select regselect" required>
                <?php
                
                foreach ($realms as $realm) {
                ?><option value=<?= $realm["idRealms"] ?>><?= $realm["nameRealm"] . " " . $realm["nameRegion"] ?></option>
                <?php
                }
                ?>
            </select>
        </div>
        <div class="form-group">
            <label for="factionCharacter">Faction</label>
            <select name="factionCharacter" id="factionCharacter" class="custom-select regselect" required>
                <?php
                
                foreach ($factions as $faction) {
                ?><option value=<?= $faction[0] ?>><?= $faction[1] ?></option>
                <?php
                }
                ?>
            </select>
        </div>
        <div class="form-group">
            <label for="classCharacter">Class</label>
            <select name="classCharacter" id="classCharacter" class="custom-select regselect" required>
                <?php
                foreach ($classes as $class) {
                ?><option value=<?= $class[0] ?>><?= $class[1] ?></option>
                <?php
                }
                ?>
            </select>
        </div>
        <div class="form-group">
            <input type="hidden" class="form-control" name="userCharacter" id="userCharacter" value="<?= $_SESSION["user"]["idUsers"] ?>" required> 
        </div>
        <button type="submit" class="btn btn-secondary">Push</button>
    </form>
</div>
<div class="container">
    <table class="table regtable">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">name</th>
                <th scope="col">class</th>
                <th scope="col">realm</th>
                <th scope="col">faction</th>
                
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($characters as $character) {
            ?>
                <tr>
                    <th scope="row"><?= $character["idCharacters"] ?></td>
                    <td><?= $character["nameCharacter"] ?></td>
                    <td><?= $character["nameClass"] ?></td>
                    <td><?= $character["nameRealm"] . " " . $character["nameRegion"] ?></td>
                    <td><?= $character["nameFaction"] ?></td>
                    <td>
                        <a class="btn btn-secondary" href="editcharacter/<?= $character["idCharacters"] ?>">Edit</a>
                        <a class="btn btn-secondary" href="editcharacter/<?= $character["idCharacters"] ?>/delete">Delete</a>
                    </td>
                </tr>
            <?php
            }
            ?>
        </tbody>
    </table>
</div>