<div class="container">
    <form method="post">
        <div class="form-group">
            <label for="nameClass">Name</label>
            <input type="text" class="form-control" name="nameClass" id="nameClass" required>
        </div>
        <button type="submit" class="btn btn-secondary">Push</button>
    </form>
</div>
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <?php
            $classes = dbget::get("classes");
            foreach ($classes as $class) {
            ?>
                <tr>
                    <th scope="row"><?= $class["idClasses"] ?></td>
                    <td><?= $class["nameClass"] ?></td>
                    <td>
                        <a class="btn btn-secondary" href="editclass/<?= $class["idClasses"] ?>">Edit</a>
                        <a class="btn btn-secondary" href="editclass/<?= $class["idClasses"] ?>/delete">Delete</a>
                    </td>
                </tr>
            <?php
            }
            ?>
        </tbody>
    </table>
</div>