<div class="container">
    <form method="post">
        <div class="form-group">
            <label for="nameDifficulty">Name</label>
            <input type="text" class="form-control" name="nameDifficulty" id="nameDifficulty" required>
        </div>
        <div class="form-group">
            <label for="pNumber">Number of Players (legacy)</label>
            <input type="text" class="form-control" name="pNumber" id="pNumber">
        </div>
        <button type="submit" class="btn btn-secondary">Push</button>
    </form>
</div>
<div class="container">
    <table class="table regtable">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Number of players</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($difficulties as $difficulty) {
            ?>
                <tr>
                    <th scope="row"><?= $difficulty["idDifficulty"] ?></td>
                    <td><?= $difficulty["nameDifficulty"] ?></td>
                    <td><?= $difficulty["pNumber"] ?></td>
                    <td>
                        <a class="btn btn-secondary" href="editdifficulty/<?= $difficulty["idDifficulty"] ?>">Edit</a>
                        <a class="btn btn-secondary" href="editdifficulty/<?= $difficulty["idDifficulty"] ?>/delete">Delete</a>
                    </td>
                </tr>
            <?php
            }
            ?>
        </tbody>
    </table>
</div>