<div class="container">
    <form method="post">
        <div class="form-group">
            <label for="nameFaction">Name</label>
            <input type="text" class="form-control" name="nameFaction" id="nameFaction" required>
        </div>
        <button type="submit" class="btn btn-secondary">Push</button>
    </form>
</div>
<div class="container">
    <table class="table regtable">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($factions as $faction) {
            ?>
                <tr>
                    <th scope="row"><?= $faction["idFactions"] ?></td>
                    <td><?= $faction["nameFaction"] ?></td>
                    <td>
                        <a class="btn btn-secondary" href="editfaction/<?= $faction["idFactions"] ?>">Edit</a>
                        <a class="btn btn-secondary" href="editfaction/<?= $faction["idFactions"] ?>/delete">Delete</a>
                    </td>
                </tr>
            <?php
            }
            ?>
        </tbody>
    </table>
</div>