<div class="container">
    <form method="post">
        <div class="form-group">
            <label for="nameRaid">Name</label>
            <input type="text" class="form-control" name="nameRaid" id="nameRaid" required>
        </div>
        <button type="submit" class="btn btn-secondary">Push</button>
    </form>
</div>
<div class="container">
    <table class="table regtable">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($raids as $raid) {
            ?>
                <tr>
                    <th scope="row"><?= $raid["idRaids"] ?></td>
                    <td><?= $raid["nameRaid"] ?></td>
                    <td>
                        <a class="btn btn-secondary" href="editraid/<?= $raid["idRaids"] ?>">Edit</a>
                        <a class="btn btn-secondary" href="editraid/<?= $raid["idRaids"] ?>/delete">Delete</a>
                    </td>
                </tr>
            <?php
            }
            ?>
        </tbody>
    </table>
</div>