<div class="container">
    <form method="post">
        <div class="form-group">
            <label for="nameRegion">Name</label>
            <input type="text" class="form-control" name="nameRegion" id="nameRegion" required>
        </div>
        <button type="submit" class="btn btn-secondary">Push</button>
    </form>
</div>
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <?php
            $regions = dbget::get("regions");
            foreach ($regions as $region) {
            ?>
                <tr>
                    <th scope="row"><?= $region["idRegions"] ?></td>
                    <td><?= $region["nameRegion"] ?></td>
                    <td>
                        <a class="btn btn-secondary" href="editregion/<?= $region["idRegions"] ?>">Edit</a>
                        <a class="btn btn-secondary" href="editregion/<?= $region["idRegions"] ?>/delete">Delete</a>
                    </td>
                </tr>
            <?php
            }
            ?>
        </tbody>
    </table>
</div>