<div class="container">
    <form method="post">
        <div class="form-group">
            <label for="idClasses">Class</label>
            <select name="idClasses" id="idClasses" class="custom-select regselect" required>
                <?php
                foreach ($classes as $class) {
                ?><option value=<?= $class[0] ?>><?= $class[1] ?></option>
                <?php
                }
                ?>
            </select> 
        </div>
        <div class="form-group">
            <label for="idTypes">Type</label>
            <select name="idTypes" id="idTypes" class="custom-select regselect" required>
                <?php
                foreach ($types as $type) {
                ?><option value=<?= $type[0] ?>><?= $type[1] ?></option>
                <?php
                }
                ?>
            </select>
        </div>
        <button type="submit" class="btn btn-secondary">Push</button>
    </form>
</div>
<div class="container">
    <table class="table regtable">
        <thead>
            <tr>
                <th scope="col">Class</th>
                <th scope="col">Type</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($typeclasses as $types) 
            {
            ?>
                <tr>
                    <td><?= $types["nameClass"] ?></td>
                    <td><?= $types["nameType"] ?></td>
                    <td>
                        <a class="btn btn-secondary" href="edittypeclass/<?= $types["idClasses"] ?>/<?= $types["idTypes"] ?>/delete">Delete</a>
                    </td>
                </tr>
            <?php
            }
            ?>
        </tbody>
    </table>
</div>