<div class="container">
    <form method="post">
        <div class="form-group">
            <label for="nameType">Name</label>
            <input type="text" class="form-control" name="nameType" id="nameType" required>
        </div>
        <button type="submit" class="btn btn-secondary">Push</button>
    </form>
</div>
<div class="container">
    <table class="table regtable">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($types as $type) {
            ?>
                <tr>
                    <th scope="row"><?= $type["idTypes"] ?></td>
                    <td><?= $type["nameType"] ?></td>
                    <td>
                        <a class="btn btn-secondary" href="edittype/<?= $type["idTypes"] ?>">Edit</a>
                        <a class="btn btn-secondary" href="edittype/<?= $type["idTypes"] ?>/delete">Delete</a>
                    </td>
                </tr>
            <?php
            }
            ?>
        </tbody>
    </table>
</div>