<div class="container">
    <form method="post">
        <div class="form-group">
            <label for="idClasses">Class</label>
            <select name="idClasses" id="idClasses" class="custom-select" required>
                <?php
                $classes = dbget::get("classes");
                foreach ($classes as $class) {
                ?><option value=<?= $class[0] ?>><?= $class[1] ?></option>
                <?php
                }
                ?>
            </select>
        </div>
        <div class="form-group">
            <label for="idTypes">Type</label>
            <select name="idTypes" id="idTypes" class="custom-select" required>
                <?php
                $types = dbget::get("types");
                foreach ($types as $type) {
                ?><option value=<?= $type[0] ?>><?= $type[1] ?></option>
                <?php
                }
                ?>
            </select>
        </div>
        <button type="submit" class="btn btn-secondary">Push</button>
    </form>
</div>
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Class</th>
                <th scope="col">Type</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <?php
            $typeclasses = dbget::get("classes_has_types");
            foreach ($typeclasses as $types) {
                $classes = dbget::toName("classes", $types["idClasses"]);
                $type = dbget::toName("types", $types["idTypes"]);
            ?>
                <tr>
                    <td><?= $classes[0] ?></td>
                    <td><?= $type[0] ?></td>
                    <td>
                        <a class="btn btn-secondary" href="edittypeclass/<?= $types["idClasses"] ?>/<?= $types["idTypes"] ?>/delete">Delete</a>
                    </td>
                </tr>
            <?php
            }
            ?>
        </tbody>
    </table>
</div>