<div class="container">
    <form method="post">
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" class="form-control" name="name" required>
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" name="password" required>
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="text" class="form-control" name="email" required>
        </div>
        <div class="form-group">
            <label for="admin">Admin</label>
            <select name="admin" class="custom-select">               
                <option value=0>Regular</option>
                <option value=1>Admin</option>
            </select>
        </div>
        <button type="submit" class="btn btn-secondary">Create</button>
    </form>
</div>
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Username</th>
                <th scope="col">Email</th>
                <th scope="col">Admin</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php
            $accs = dbget::get("Accounts");
            foreach ($accs as $acc) {
            ?>
                <tr>
                    <th scope="row"><?= $acc["idAccounts"] ?></td>
                    <td><?= $acc["name"] ?></td>
                    <td><?= $acc["email"] ?></td>
                    <td><?= $acc["admin"] ?></td>
                    <td>
                        <a class="btn btn-secondary" href="edituser/<?= $acc["idAccounts"] ?>">Edit</a>
                        <a class="btn btn-secondary" href="edituser/<?= $acc["idAccounts"] ?>/delete">Delete</a>
                    </td>
                </tr>
            <?php
            }
            ?>
        </tbody>
    </table>
</div>