
<div class="container">
    <table class="table regtable">
        <thead>
            <tr>
                <th scope="col">name</th>
            </tr>
        </thead>
        <tbody>
        <?php
        foreach($items as $item)
        {?>
            <tr>
                <td><?= $item[1] ?></td>       
            </tr>
        <?php
        }
        ?>
        </tbody>
    </table>
</div>