
<div class="container">
    <table class="table regtable">
        <thead>
            <tr>
                <th scope="col">name</th>
                <th scope="col">class</th>
            </tr>
        </thead>
        <tbody>
        <?php
        foreach($items as $item)
        {?>
            <tr>
                <td><a style="color:inherit; text-decoration: none;" href="item/<?= text::from_camel(text::camelCase($item["nameItem"])) ?>"><?= $item["nameItem"] ?></a></td>
                <td><?= $item["nameClass"] ?></td>    
            </tr>
        <?php
        }
        ?>
        </tbody>
    </table>
</div>