<?php $realm = dbget::getByID("realms", $id); ?>
<div class="container">
    <form method="post">
        <div class="form-group">
            <label for="nameRealm">Name</label>
            <input type="text" class="form-control" name="nameRealm" value="<?= $realm[1] ?>" required>
        </div>
        <div class="form-group">
            <label for="regionRealm">Region</label>
            <select name="regionRealm" class="custom-select regselect" required>
                <?php
                $regions = dbget::get("regions");
                foreach ($regions as $region) {
                ?><option value=<?= $region[0] ?> <?php if($realm[2] == $region[0]){ echo "selected";} ?>><?= $region[1] ?></option>
                <?php
                }
                ?>
            </select>
        </div>
        <button type="submit" class="btn btn-secondary">Push</button>
    </form>
</div>