<?php $raid = dbget::getByID("raids", $id); ?>
<div class="container">
    <form method="post">
        <div class="form-group">
            <label for="nameRaid">Name</label>
            <input type="text" class="form-control" name="nameRaid" id="nameRaid" value="<?= $raid[1] ?>" required>
        </div>
        <button type="submit" class="btn btn-secondary">Push</button>
    </form>
</div>