<?php $accs = dbget::getByID("accounts", $id); ?>
<div class="container">
    <form method="post">
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" class="form-control" name="name" value="<?= $accs[1] ?>" required>
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" name="password" >
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="text" class="form-control" name="email" value="<?= $accs[2] ?>" required>
        </div>
        <div class="form-group">
            <label for="admin">Admin</label>
            <select name="admin" class="custom-select">               
                <option value=0 <?php if($accs[4] == 0){ echo "selected"; } ?>>Regular</option>
                <option value=1 <?php if($accs[4] == 1){ echo "selected"; } ?>>Admin</option>
            </select>
        </div>
        <button type="submit" class="btn btn-secondary">Push</button>
    </form>
</div>