<?php 
$b = dbget::getByID("bosses", $id); ?>
<div class="container">
    <form method="post">
        <div class="form-group">
            <label for="nameBoss">Name</label>
            <input type="text" class="form-control" name="nameBoss" value="<?= $b[1] ?>" required>
        </div>
        <div class="form-group">
            <label for="difficulty">Difficulty</label>
            <select name="difficulty" class="custom-select regselect">   
                <?php
                $classes = dbget::get("difficulty");
                foreach ($classes as $class) {
                ?><option value=<?= $class[0] ?> <?php if($b[2] == $class[0]){ echo "selected";} ?>><?= $class[1] ?></option>
                <?php
                }
                ?>
            </select>
        </div>
        <div class="form-group">
            <label for="raid">Raid</label>
            <select name="raid" class="custom-select regselect">   
                <?php
                $classes = dbget::get("raids");
                foreach ($classes as $class) {
                ?><option value=<?= $class[0] ?> <?php if($b[3] == $class[0]){ echo "selected";} ?>><?= $class[1] ?></option>
                <?php
                }
                ?>
            </select>
        </div>
        <button type="submit" class="btn btn-secondary">Push</button>
    </form>
</div>