
<div class="container">
    <form method="post">
        <div class="form-group">
            <label for="nameCharacter">Name</label>
            <input type="text" class="form-control" name="nameCharacter" value="<?= $chars[1] ?>" required>
        </div>
        <div class="form-group">
            <label for="realmCharacter">Realm</label>
            <select name="realmCharacter" class="custom-select regselect" required>
                <?php
                foreach ($realms as $realm) {
                ?><option value=<?= $realm[0] ?> <?php if($chars[2] == $realm[0]){ echo "selected";} ?>><?= $realm[1] ?></option>
                <?php
                }
                ?>
            </select>
        </div>
        <div class="form-group">
            <label for="factionCharacter">Faction</label>
            <select name="factionCharacter" class="custom-select regselect" required>
                <?php
                foreach ($factions as $faction) {
                ?><option value=<?= $faction[0] ?> <?php if($chars[3] == $faction[0]){ echo "selected";} ?>><?= $faction[1] ?></option>
                <?php
                }
                ?>
            </select>
        </div>
        <div class="form-group">
            <label for="classCharacter">Class</label>
            <select name="classCharacter" class="custom-select regselect" required>
                <?php
                foreach ($classes as $class) {
                ?><option value=<?= $class[0] ?> <?php if($chars[4] == $class[0]){ echo "selected";} ?>><?= $class[1] ?></option>
                <?php
                }
                ?>
            </select>
        </div>
        <button type="submit" class="btn btn-secondary">Push</button>
    </form>
</div>