
<div class="container">
    <form method="post">
        <div class="form-group">
            <label for="nameDifficulty">Name</label>
            <input type="text" class="form-control" name="nameDifficulty" value="<?= $diff[1] ?>" required>
        </div>
        <div class="form-group">
            <label for="pNumber">Number of Players</label>
            <input type="text" class="form-control" name="pNumber" id="pNumber" value="<?= $diff[2] ?>" >
        </div>
        <button type="submit" class="btn btn-secondary">Push</button>
    </form>
</div>