<?php $accs = dbget::getByID("accounts", $_SESSION["user"]["idAccounts"]); ?>
<div class="container">
    <form method="post">
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" class="form-control" name="name" value="<?= $accs[1] ?>" required>
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" name="password">
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="text" class="form-control" name="email" value="<?= $accs[2] ?>" required>
        </div>
        <button type="submit" class="btn btn-secondary">Push</button>
    </form>
</div>