<div class="container">
    <form method="post">
        <div class="form-group">
            <label for="nameBoss">Name</label>
            <input type="text" class="form-control" name="nameBoss" value="<?= $b[1] ?>" required>
        </div>
        <div class="form-group">
            <label for="difficulty">Difficulty</label>
            <select name="difficulty" class="custom-select regselect">   
                <?php
                foreach ($difficulties as $diff) {
                ?><option value=<?= $diff[0] ?> <?php if($b[2] == $diff[0]){ echo "selected";} ?>><?= $diff[1] ?></option>
                <?php
                }
                ?>
            </select>
        </div>
        <div class="form-group">
            <label for="raid">Raid</label>
            <select name="raid" class="custom-select regselect">   
                <?php
                foreach ($raids as $raid) {
                ?><option value=<?= $raid[0] ?> <?php if($b[3] == $raid[0]){ echo "selected";} ?>><?= $raid[1] ?></option>
                <?php
                }
                ?>
            </select>
        </div>
        <button type="submit" class="btn btn-secondary">Push</button>
    </form>
</div>