
<div class="container">
    <table class="table regtable">
        <thead>
            <tr>
                <th scope="col">name</th>
                <th scope="col">raid</th>
            </tr>
        </thead>
        <tbody>
        <?php
        foreach($bosses as $boss)
        {?>
            <tr>
                <td><a style="color:inherit; text-decoration: none;" href="boss/<?= text::from_camel(text::camelCase($boss["nameBoss"])) ?>/<?= $boss["difficulty"] ?>"><?= $boss["nameBoss"] . " " . $boss["nameDifficulty"] ?></a></td>     
                <td><a style="color:inherit; text-decoration: none;" href="raid/<?= text::from_camel(text::camelCase($boss["nameRaid"])) ?>"><?= $boss["nameRaid"] ?></a></td>
            </tr>
        <?php
        }
        ?>
        </tbody>
    </table>
</div>