<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport">
    <base href="/">
    <link rel="stylesheet" href="bootstrap.min.css">    
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css" type="text/css">
    <link rel="stylesheet" href="customstyle.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
    <script>
                $(document).ready(function() {
                    $('.regselect').select2();
                    $('.regtable').DataTable();
                });
    </script>
    <title>tmogRunner</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="intro">tmogRunner</a>
        <div class="navbar-nav navbar-collapse collapse container-fluid">
            <div class="d-inline-flex">
                <a class="nav-item nav-link" href="items">Items</a>
                <a class="nav-item nav-link" href="raids">Raids</a>
                <div class="nav-item dropdown">
                    <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="navbarDropdown" role="button">
                        Menu
                    </a>
                    <div aria-labelledby="navbarDropdownMenuLink" class="dropdown-menu">
                        <?php
                        if (isset($_SESSION["user"])) {
                        ?>
                            <?php
                            if ($_SESSION["user"]["admin"] == 1) {
                            ?>
                                <a class="dropdown-item" href="adddifficulty">Add Difficulty</a>
                                <a class="dropdown-item" href="additem">Add Item</a>
                                <a class="dropdown-item" href="addraid">Add Raid</a>
                                <a class="dropdown-item" href="addboss">Add Boss</a>
                                <a class="dropdown-item" href="addtype">Add Type</a>
                                <a class="dropdown-item" href="addregion">Add Region</a>
                                <a class="dropdown-item" href="addfaction">Add Faction</a>
                                <a class="dropdown-item" href="addrealm">Add Realm</a>
                                <a class="dropdown-item" href="addclass">Add Class</a>
                                <a class="dropdown-item" href="addtypeclass">Add TypeClass</a>
                                <a class="dropdown-item" href="addbossitem">Add BossItem</a>
                                <a class="dropdown-item" href="adduser">Users</a>
                            <?php
                            } ?>
                            <a class="dropdown-item" href="addcharacter">Add Character</a>
                            <a class="dropdown-item" href="favorite">Favorite</a>
                            <a class="dropdown-item" href="edit">Edit User</a>
                            <a class="dropdown-item" href="logout">Log out</a>
                        <?php
                        } else {
                        ?>
                            <a class="dropdown-item" href="signup">Sign up</a>
                            <a class="dropdown-item" href="login">Log in</a>
                        <?php
                        }

                        ?>
                    </div>

                </div>
            </div>
            <div>
                <?php
                if (isset($_SESSION["user"])) {
                ?>
                    <p class="d-inline my-2">User: <?= $_SESSION["user"]["name"] ?></p>

                <?php
                }
                ?>
            </div>
        </div>
    </nav>
    <main>
        <div class="container-fluid">
            <?php
            $this->controller->printView();
            ?>
        </div>
    </main>
        </body>
</html>