<div class="container">
    <table class="table regtable">
        <thead>
            <tr>
                <th scope="col">name</th>
            </tr>
        </thead>
        <tbody>
        <?php 
        foreach($raids as $raid)
        {?>
            <tr>
                <td><a style="color:inherit; text-decoration: none;" href="raid/<?= text::from_camel(text::camelCase($raid["nameRaid"])) ?>"><?= $raid["nameRaid"] ?></a></td>       
            </tr>
        <?php
        }
        ?>
        </tbody>
    </table>
</div>