<?php
if (isset($_POST["favRaid"])) {
    $sql = "INSERT INTO FavoriteRaid
(idRaid, idUser) VALUES
('{$_POST["favRaid"]}', '{$_SESSION["user"]["idUser"]}')";

    mysqli_query($conn, $sql);
    header("Location: Raids.php");
}
?>
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">name</th>
            </tr>
        </thead>
        <tbody>
        <?php 
        $raids = dbget::get("raids");
        foreach($raids as $raid)
        {?>
            <tr>
                <td><a style="color:inherit; text-decoration: none;" href="raid/<?= text::from_camel(text::camelCase($raid["nameRaid"])) ?>"><?= $raid["nameRaid"] ?></a></td>       
            </tr>
        <?php
        }
        ?>
        </tbody>
    </table>
</div>