<div class="container">
    <table class="table regtable">
        <thead>
            <tr>
                <th scope="col">name</th>
            </tr>
        </thead>
        <tbody>
        <?php 
        foreach($bosses as $boss)
        { ?>
            <tr>
                <td><a style="color:inherit; text-decoration: none;" href="boss/<?= text::from_camel(text::camelCase($boss["nameBoss"])) . "/" . $boss[2] ?>"><?= $boss[1] . " " . $boss["nameDifficulty"] ?></a></td>       
            </tr>
        <?php
        }
        ?>
        </tbody>
    </table>
</div>