<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">name</th>
            </tr>
        </thead>
        <tbody>
        <?php 
        $bosses = dbget::get("bosses");
        foreach($bosses as $boss)
        {
            $d = dbget::toName("difficulty", $boss[2])?>
            <tr>
                <td><a style="color:inherit; text-decoration: none;" href="boss/<?= text::from_camel(text::camelCase($boss["nameBoss"])) . "/" . $boss[2] ?>"><?= $boss[1] . " " . $d[0] ?></a></td>       
            </tr>
        <?php
        }
        ?>
        </tbody>
    </table>
</div>